---
  hosts: all
  tasks:
    - file:
        path: /tmp/ansi.txt
        state: touch
        mode: 777

    - copy:
        src: /etc/fstab
        dest: /tmp/cpfstab
        mode: 700
        owner: manage
        group: manage

    - file:
        path: /var/ptm
        state: directory
        mode: 755

    - copy:
        src: /etc/fstab
        dest: /var/ptm/cpfstab
    
    - user:
        name: doc1
        state: present
        uid: 5000

    - yum:
        name: autofs
        state: present

    - service:
        name: autofs
        state: start
        enabled: yes