---
- name: example of command line variable
  hosts:  all
  tasks:  
    - name: create user
      user:
        name: "{{ us }}"
        state: "{{ st }}"
        # password: "{{ pass }}"
        password: "{{ pass | password_hash('sha512')}}"

    - name: installing package
      yum:
        name: "{{ pack }}"
        state: "{{ st }}"