--- 
- name: import task file playbook 
  hosts: all
  tasks:
    - name: copy /etc/fstab to /tmp/vsfstab
      copy: 
        src: /etc/fstab
        dest: /tmp/vsfstab
        mode: '0444'

    - name: import task from /home/controller/ansible-playbook/5ImportTaskFile/onlytask.yaml
      import_tasks: /home/controller/ansible-playbook/5ImportTaskFile/onlytask.yaml
      