---
- name: example of register variable
  hosts:  all
  tasks:  
    - name: check available disk
      command: lsblk
      register: disk
    
    - name: show output of command
      debug:
        msg:
          - "command output: {{disk.stdout_lines}}" 
          - " return code: {{disk.rc}}"